development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: darth-vader-api_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: darth-vader-api_test
  pool: 5
  username: root
  password:

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: darth-vader-api_staging
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
